BOT_MESSAGES_RESPONSE = [
"JULIANA?!",
"Bruno? Embaixo da ponte?",
"faz isso comigo não, velho",
"gente, quantos anos eu tenho?",
"felipe!",
"smith!",
"16 18",
"seu cu",
"JARBAS?!",
"ADRIANO?",
"Meu braço ta branco, velho!",
"Guarapari, Búzios é minha arte",
"brigado",
"RAVE?!",
"Marcelo não..",
"Minha vida!",
"Eu não sei nem onde eu tô, véi",
"Antonela Caroline, meu gol?",
"Cristiano Ronaldo?",
"Minha arte PC Gusmão",
"Milton Nascimento, velho",
"O MEU PAI?!",
"Sai dae, doido! Cê é mó playboy!",
"É óbvio, velho!",
"Romero Britto?!",
"meu braço, velho! Vai quebrar! O meu braço!",
"samu?",
"arquitetura?",
"( ͡° ͜ʖ ͡°)",
"ᕦ( ͡° ͜ʖ ͡°)ᕤ",
"mata o papai",
'e daí?',
'se eu to chamando?',
'brigado',
'hahahah.. não',
"samu?",
'ᕦ( ͡° ͜ʖ ͡°)ᕤ',
'é óbvio, velho!',
'culpa da dilma',
'podia ser pior...',
'rs',
'pera',
'viaja não',
'sei lá',
'não sei',
'que?',
'eae',
'oi',
'não',
'cê é o bichão memo, hein doido',
'sim',
'calma',
'partiu almoço',
':D',
':(',
'valeu',
'nada a ver',
'¬¬',
':´(',
'depende.. ( ͡° ͜ʖ ͡°)',
'25 reais é 25 reais.. ( ͡° ͜ʖ ͡°)'
]